// <auto-generated />
using System;
using EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebService.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20251224012759_i2AddBlogSeed")]
    partial class i2AddBlogSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Content = "# C# 10 新特性\n\nC# 10 带来了许多令人兴奋的新特性，包括全局 using 指令、文件范围的命名空间、常量内插字符串等，极大提升了开发效率。",
                            CreatedAt = new DateTime(2024, 1, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "深入探讨 C# 10 带来的新功能和改进",
                            TagsJson = "[\"C#\",\".NET\",\"\\u7F16\\u7A0B\"]",
                            Title = "C# 10 新特性详解"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Content = "# Entity Framework Core 入门\n\nEF Core 是 .NET 平台下的 ORM 框架，支持多种数据库提供程序，简化了数据访问层的开发工作。",
                            CreatedAt = new DateTime(2024, 1, 12, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            Description = "从零开始学习 EF Core 的基本用法",
                            TagsJson = "[\"EF Core\",\"\\u6570\\u636E\\u5E93\",\"ORM\",\"\\u6559\\u7A0B\"]",
                            Title = "Entity Framework Core 入门指南"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Content = "# Web API 最佳实践\n\n1. 使用依赖注入\n2. 实现异常处理中间件\n3. 添加请求验证\n4. 使用适当的 HTTP 状态码\n5. 实现缓存机制提升性能",
                            CreatedAt = new DateTime(2024, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "构建高性能 Web API 的建议和技巧",
                            TagsJson = "[\"ASP.NET Core\",\"Web API\",\"RESTful\"]",
                            Title = "ASP.NET Core Web API 最佳实践"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            Content = "# MySQL 优化\n\n## 索引优化\n\n合理创建索引可以显著提升查询性能，但过多的索引会影响写入操作。本文详细讲解索引设计原则和优化方法。",
                            CreatedAt = new DateTime(2024, 1, 18, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "提升 MySQL 数据库性能的实用方法",
                            TagsJson = "[\"MySQL\",\"\\u6570\\u636E\\u5E93\",\"\\u4F18\\u5316\",\"\\u6027\\u80FD\"]",
                            Title = "MySQL 优化技巧"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            Content = "# 依赖注入详解\n\n依赖注入是现代 .NET 应用的核心模式，通过控制反转(IoC)容器管理对象生命周期，提高代码的可测试性和可维护性。",
                            CreatedAt = new DateTime(2024, 1, 20, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "掌握 .NET 依赖注入的核心概念和应用",
                            TagsJson = "[\".NET\",\"\\u4F9D\\u8D56\\u6CE8\\u5165\",\"\\u8BBE\\u8BA1\\u6A21\\u5F0F\"]",
                            Title = ".NET 依赖注入深入理解"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Content = "# 异步编程指南\n\n异步编程可以避免线程阻塞，提升应用吞吐量。本文讲解异步编程的核心原则、常见陷阱和性能优化技巧。",
                            CreatedAt = new DateTime(2024, 1, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "正确使用 async/await 提升应用响应能力",
                            TagsJson = "[\"C#\",\"\\u5F02\\u6B65\\u7F16\\u7A0B\",\"\\u6027\\u80FD\\u4F18\\u5316\"]",
                            Title = "异步编程在 C# 中的最佳实践"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            Content = "# 中间件开发\n\n中间件是处理 HTTP 请求的组件管道，本文详细介绍如何创建、配置和使用自定义中间件，以及中间件的执行顺序。",
                            CreatedAt = new DateTime(2024, 1, 25, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "自定义中间件实现请求处理逻辑",
                            TagsJson = "[\"ASP.NET Core\",\"\\u4E2D\\u95F4\\u4EF6\",\"HTTP\",\"\\u7BA1\\u9053\"]",
                            Title = "ASP.NET Core 中间件开发详解"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Content = "# Redis 缓存实战\n\nRedis 是高性能的键值存储系统，本文讲解如何在 .NET 应用中集成 Redis、实现数据缓存和分布式锁。",
                            CreatedAt = new DateTime(2024, 1, 28, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "使用 Redis 提升 .NET 应用性能",
                            TagsJson = "[\"Redis\",\"\\u7F13\\u5B58\",\".NET\",\"\\u6027\\u80FD\"]",
                            Title = "Redis 缓存在 .NET 中的应用"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            Content = "# 单例模式详解\n\n单例模式确保一个类只有一个实例，并提供全局访问点。本文对比懒汉式、饿汉式、双重检查锁定等多种实现方式的优缺点。",
                            CreatedAt = new DateTime(2024, 2, 1, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "深入理解单例模式的多种实现方式",
                            TagsJson = "[\"C#\",\"\\u8BBE\\u8BA1\\u6A21\\u5F0F\",\"\\u5355\\u4F8B\\u6A21\\u5F0F\"]",
                            Title = "C# 设计模式之单例模式"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 2,
                            Content = "# .NET 6 性能调优\n\n.NET 6 带来了显著的性能提升，但合理的代码编写和配置仍然至关重要。本文分享内存管理、GC 优化和代码优化的实用技巧。",
                            CreatedAt = new DateTime(2024, 2, 3, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Description = "提升 .NET 6 应用性能的实用方法",
                            TagsJson = "[\".NET 6\",\"\\u6027\\u80FD\\u4F18\\u5316\",\"\\u5185\\u5B58\\u7BA1\\u7406\"]",
                            Title = ".NET 6 性能优化技巧"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            Content = "# EF Core 迁移\n\nEF Core 迁移允许你以代码优先的方式管理数据库架构变更，本文讲解迁移的创建、应用、回滚和团队协作技巧。",
                            CreatedAt = new DateTime(2024, 2, 5, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "管理数据库架构变更的最佳实践",
                            TagsJson = "[\"EF Core\",\"\\u6570\\u636E\\u5E93\\u8FC1\\u79FB\",\"\\u7248\\u672C\\u63A7\\u5236\"]",
                            Title = "EF Core 迁移和数据库版本控制"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 1,
                            Content = "# 身份验证与授权\n\n本文详细讲解如何在 ASP.NET Core 中实现 JWT 认证、基于角色和基于策略的授权，保护你的 Web 应用安全。",
                            CreatedAt = new DateTime(2024, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "实现安全的用户认证和权限管理",
                            TagsJson = "[\"ASP.NET Core\",\"\\u8BA4\\u8BC1\",\"\\u6388\\u6743\",\"JWT\"]",
                            Title = "ASP.NET Core 身份验证与授权"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 2,
                            Content = "# LINQ 性能优化\n\nLINQ 提供了强大的查询能力，但不当的使用会导致性能问题。本文讲解延迟执行、查询转换和避免常见性能陷阱的方法。",
                            CreatedAt = new DateTime(2024, 2, 10, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "编写高性能的 LINQ 查询",
                            TagsJson = "[\"LINQ\",\"C#\",\"\\u6027\\u80FD\\u4F18\\u5316\",\"\\u67E5\\u8BE2\"]",
                            Title = "LINQ 查询优化技巧"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            Content = "# 配置管理\n\n.NET Core 提供了统一的配置系统，支持多种配置源。本文讲解配置的加载、验证、热更新和环境特定配置的最佳实践。",
                            CreatedAt = new DateTime(2024, 2, 12, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "灵活管理应用配置的方法",
                            TagsJson = "[\".NET Core\",\"\\u914D\\u7F6E\",\"\\u73AF\\u5883\\u53D8\\u91CF\",\"appsettings\"]",
                            Title = ".NET Core 配置管理最佳实践"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 1,
                            Content = "# 委托与事件\n\n委托是类型安全的函数指针，事件是委托的特殊应用。本文通过实例讲解委托和事件的使用场景和实现原理。",
                            CreatedAt = new DateTime(2024, 2, 15, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "理解委托、事件和回调的核心概念",
                            TagsJson = "[\"C#\",\"\\u59D4\\u6258\",\"\\u4E8B\\u4EF6\",\"\\u56DE\\u8C03\"]",
                            Title = "C# 委托和事件详解"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 2,
                            Content = "# 日志记录指南\n\n良好的日志系统是排查问题的关键。本文讲解如何配置日志提供程序、设置日志级别、结构化日志和日志聚合的最佳实践。",
                            CreatedAt = new DateTime(2024, 2, 18, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "构建完善的日志系统",
                            TagsJson = "[\"ASP.NET Core\",\"\\u65E5\\u5FD7\",\"\\u8BCA\\u65AD\",\"Serilog\"]",
                            Title = "ASP.NET Core 日志记录最佳实践"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 3,
                            Content = "# xUnit 单元测试\n\nxUnit 是 .NET 生态中主流的测试框架，本文讲解测试的基本原则、断言使用、测试夹具和数据驱动测试的实现方法。",
                            CreatedAt = new DateTime(2024, 2, 20, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "编写可靠的单元测试保障代码质量",
                            TagsJson = "[\"xUnit\",\"\\u5355\\u5143\\u6D4B\\u8BD5\",\".NET\",\"TDD\"]",
                            Title = "使用 xUnit 进行 .NET 单元测试"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 1,
                            Content = "# 内存管理详解\n\n了解 .NET 垃圾回收器的工作原理、代龄机制、大对象堆和内存泄漏排查方法，帮助你编写更高效的代码。",
                            CreatedAt = new DateTime(2024, 2, 22, 16, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "深入理解 CLR 内存管理机制",
                            TagsJson = "[\".NET\",\"\\u5185\\u5B58\\u7BA1\\u7406\",\"GC\",\"\\u6027\\u80FD\"]",
                            Title = ".NET 中的内存管理与垃圾回收"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 2,
                            Content = "# CORS 配置\n\n跨域资源共享是现代 Web 应用的常见需求。本文详细讲解 CORS 原理、ASP.NET Core 中的配置方法和安全最佳实践。",
                            CreatedAt = new DateTime(2024, 2, 25, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "解决 CORS 问题的完整指南",
                            TagsJson = "[\"ASP.NET Core\",\"CORS\",\"\\u8DE8\\u57DF\",\"Web \\u5F00\\u53D1\"]",
                            Title = "ASP.NET Core 跨域请求处理"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 3,
                            Content = "# .NET 7 升级指南\n\n.NET 7 带来了更多性能改进和新功能。本文讲解主要新特性、升级步骤、兼容性问题和最佳实践。",
                            CreatedAt = new DateTime(2024, 2, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "从 .NET 6 迁移到 .NET 7 的注意事项",
                            TagsJson = "[\".NET 7\",\"\\u5347\\u7EA7\",\"\\u65B0\\u7279\\u6027\",\"\\u8FC1\\u79FB\"]",
                            Title = ".NET 7 新特性与升级指南"
                        });
                });

            modelBuilder.Entity("Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9622),
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9644),
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9647),
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9649),
                            Name = "Entity Framework"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9651),
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9653),
                            Name = "数据库"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9655),
                            Name = "编程"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9657),
                            Name = "教程"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9659),
                            Name = "优化"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9662),
                            Name = "Web API"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9664),
                            Name = "RESTful"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9666),
                            Name = "依赖注入"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9669),
                            Name = "设计模式"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9671),
                            Name = "ORM"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 12, 24, 9, 27, 58, 627, DateTimeKind.Local).AddTicks(9673),
                            Name = "性能"
                        });
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("motto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            Username = "admin",
                            motto = "路漫漫其修远兮，吾将上下而求索"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tech@example.com",
                            Username = "techwriter",
                            motto = "分享知识，传递价值"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dev@example.com",
                            Username = "devlover",
                            motto = "代码改变世界"
                        });
                });

            modelBuilder.Entity("Entities.Blog", b =>
                {
                    b.HasOne("Entities.User", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
