// <auto-generated />
using System;
using EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebService.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20251222025402_i1")]
    partial class i1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Content = "# C# 10 新特性\n\nC# 10 带来了许多令人兴奋的新特性...",
                            CreatedAt = new DateTime(2024, 1, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "深入探讨 C# 10 带来的新功能和改进",
                            TagsJson = "[\"C#\",\".NET\",\"\\u7F16\\u7A0B\"]",
                            Title = "C# 10 新特性详解"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Content = "# Entity Framework Core 入门\n\nEF Core 是 .NET 平台下的 ORM 框架...",
                            CreatedAt = new DateTime(2024, 1, 12, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            Description = "从零开始学习 EF Core 的基本用法",
                            TagsJson = "[\"EF Core\",\"\\u6570\\u636E\\u5E93\",\"ORM\",\"\\u6559\\u7A0B\"]",
                            Title = "Entity Framework Core 入门指南"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Content = "# Web API 最佳实践\n\n1. 使用依赖注入\n2. 实现异常处理中间件...",
                            CreatedAt = new DateTime(2024, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "构建高性能 Web API 的建议和技巧",
                            TagsJson = "[\"ASP.NET Core\",\"Web API\",\"RESTful\"]",
                            Title = "ASP.NET Core Web API 最佳实践"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            Content = "# MySQL 优化\n\n## 索引优化\n\n合理创建索引可以显著提升查询性能...",
                            CreatedAt = new DateTime(2024, 1, 18, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "提升 MySQL 数据库性能的实用方法",
                            TagsJson = "[\"MySQL\",\"\\u6570\\u636E\\u5E93\",\"\\u4F18\\u5316\",\"\\u6027\\u80FD\"]",
                            Title = "MySQL 优化技巧"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            Content = "# 依赖注入详解\n\n依赖注入是现代 .NET 应用的核心模式...",
                            CreatedAt = new DateTime(2024, 1, 20, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "掌握 .NET 依赖注入的核心概念和应用",
                            TagsJson = "[\".NET\",\"\\u4F9D\\u8D56\\u6CE8\\u5165\",\"\\u8BBE\\u8BA1\\u6A21\\u5F0F\"]",
                            Title = ".NET 依赖注入深入理解"
                        });
                });

            modelBuilder.Entity("Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(596),
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(613),
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(614),
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(615),
                            Name = "Entity Framework"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(616),
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(617),
                            Name = "数据库"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(618),
                            Name = "编程"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(664),
                            Name = "教程"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(665),
                            Name = "优化"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(666),
                            Name = "Web API"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(667),
                            Name = "RESTful"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(668),
                            Name = "依赖注入"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(669),
                            Name = "设计模式"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(670),
                            Name = "ORM"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 12, 22, 10, 54, 2, 386, DateTimeKind.Local).AddTicks(670),
                            Name = "性能"
                        });
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("motto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            Username = "admin",
                            motto = "路漫漫其修远兮，吾将上下而求索"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tech@example.com",
                            Username = "techwriter",
                            motto = "分享知识，传递价值"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dev@example.com",
                            Username = "devlover",
                            motto = "代码改变世界"
                        });
                });

            modelBuilder.Entity("Entities.Blog", b =>
                {
                    b.HasOne("Entities.User", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
